site_name: GitHub使用方法ß
nav:
    - 目次: aboud.md
    - Gitについて: Git.md
    - Git初期設定: Git-inisial.md
    - GitHubを利用したワークフロー: github-workflow.md
    - GitHub Container Registry: github-container-registry.md
dev_addr: 0.0.0.0:8000
theme:
    name: "material"
    language: "ja"
    palette:
        primary: blue
        accent: cyan
    features:
        - navigation.instant
        - navigation.tabs
        - navigation.top
        - toc.integrate
        - header.autohide
extra:
    search:
        language: "jp"
markdown_extensions:
    - admonition
    - codehilite:
          noclasses: true
          pygments_style: colorful
          linenums: true
